### ISSUE TITLE
Todo for the first release

### ISSUE THREAD

**Issue by prasann** [prasann/aka-prefixer#1]
- [x] Clean up the code. Try using async/await
- [x] Create a page to manage these stored terms
- [x] Add instructions to override shortcuts
- [x] Get a nice favicon
- [x] Put out a doc page
- [x] Update manifest with details
- [x] Package and publish the chrome extension
